security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        session_user_provider:
            id: App\Security\SessionUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: session_user_provider
            guard:
                authenticators:
                    - App\Security\Authenticator
            logout:
                path: logout

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }