version: '3'

services:
  database:
    image: mysql:5.7
    container_name: questions_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql

  php-fpm:
    image: ivanuskov/symfony4-php-fpm
    container_name: questions_app
    restart: always
    stdin_open: true
    tty: true
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./../:/var/www
  nginx:
    image: ivanuskov/symfony4-nginx
    container_name: questions_nginx
    restart: always
    volumes:
      - ./../public:/var/www
      - ./nginx.conf:/etc/nginx/sites-available/nginx.conf
      - ./nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"