homepage:
  path: /
  controller: App\Controller\HomeController::home

melogram:
  path: /melogram
  controller: App\Controller\MelogramController::page

remove_melogram:
  path: /melogram/remove/{id}
  controller: App\Controller\MelogramController::remove
  requirements:
    id: '\d+'

edit_melogram:
  path: /melogram/edit/{id}
  controller: App\Controller\MelogramController::edit
  requirements:
    id: '\d+'

add_melogram_ajax:
  path: /melogram/ajax
  controller: App\Controller\MelogramController::addAjax

edit_melogram_ajax:
  path: /melogram/ajax/{id}
  controller: App\Controller\MelogramController::editAjax
  requirements:
    id: '\d+'