homepage:
  path: /
  controller: App\Controller\HomeController::home

login:
  path: /login
  controller: App\Controller\HomeController::login

logout:
  path: /logout
  controller: App\Controller\HomeController::logout

melogram:
  path: /melogram
  controller: App\Controller\MelogramController::page

export_melogram:
  path: /melogram/export/{id}
  controller: App\Controller\MelogramController::export
  requirements:
    id: '\d+'

graph:
  path: /graph
  controller: App\Controller\GraphController::graph

remove_melogram:
  path: /melogram/remove/{id}
  controller: App\Controller\MelogramController::remove
  requirements:
    id: '\d+'

edit_melogram:
  path: /melogram/edit/{id}
  controller: App\Controller\MelogramController::edit
  requirements:
    id: '\d+'

add_melogram_ajax:
  path: /melogram/ajax
  controller: App\Controller\MelogramController::addAjax

edit_melogram_ajax:
  path: /melogram/ajax/{id}
  controller: App\Controller\MelogramController::editAjax
  requirements:
    id: '\d+'

sample:
  path: /selection
  controller: App\Controller\SampleController::sample

sample_result:
  path: /selection/result
  controller: App\Controller\SampleResultController::result

selections_view:
  path: /selections
  controller: App\Controller\SampleController:selections