homepage:
  path: /
  controller: App\Controller\HomeController::home

melogram:
  path: /melogram
  controller: App\Controller\MelogramController::page

melogram_ajax:
  path: /melogram/ajax
  controller: App\Controller\MelogramController::ajax