homepage:
  path: /
  controller: App\Controller\HomeController::home

login:
  path: /login
  controller: App\Controller\HomeController::login

logout:
  path: /logout
  controller: App\Controller\HomeController::logout

melogram:
  path: /melogram
  controller: App\Controller\MelogramController::page

export_melogram:
  path: /melogram/export/{id}
  controller: App\Controller\MelogramController::export
  requirements:
    id: '\d+'

remove_melogram:
  path: /melogram/remove/{id}
  controller: App\Controller\MelogramController::remove
  requirements:
    id: '\d+'

edit_melogram:
  path: /melogram/edit/{id}
  controller: App\Controller\MelogramController::edit
  requirements:
    id: '\d+'

add_melogram_ajax:
  path: /melogram/ajax
  controller: App\Controller\MelogramController::addAjax

edit_melogram_ajax:
  path: /melogram/ajax/{id}
  controller: App\Controller\MelogramController::editAjax
  requirements:
    id: '\d+'

selection:
  path: /selection
  controller: App\Controller\SelectionController::selection

add_selection:
  path: /selection/add
  controller: App\Controller\SelectionController::add

remove_selection:
  path: /selection/remove/{id}
  controller: App\Controller\SelectionController::remove
  requirements:
    id: '\d+'

view_selection:
  path: /selection/view/{id}
  controller: App\Controller\SelectionResultController::view
  requirements:
    id: '\d+'

selection_result:
  path: /selection/result
  controller: App\Controller\SelectionResultController::result

selections_list:
  path: /selections
  controller: App\Controller\SelectionController:selections

add_selection_group:
  path: /selection/group/add
  controller: App\Controller\SelectionGroupController::add

add_selection_group_preview:
  path: /selection/group/preview
  controller: App\Controller\SelectionGroupController::preview

selection_groups_list:
  path: /selection/group/list
  controller: App\Controller\SelectionGroupController::list

remove_selection_group:
  path: /selection/group/remove/{id}
  controller: App\Controller\SelectionGroupController::remove
  requirements:
    id: '\d+'

view_selection_group:
  path: /selection/group/view/{id}
  controller: App\Controller\SelectionGroupController::view
  requirements:
    id: '\d+'