@startuml UseCase
left to right direction
skinparam packageStyle rect
actor Оператор
actor Аналитик
rectangle ЭМАП {
   Оператор-- (Войти в систему)
   (Войти в систему) .> (Проверить логин и пароль) : include
  (Отобразить ошибку входа) .> (Войти в систему) : extends
   Оператор-- (Создать особь)
   (Отобразить ошибку "Отсутствует мелограмма для особи") .> (Создать особь) : extends
   Оператор-- (Редактировать особь)
   (Войти в систему) -- Аналитик  
   (Просмотр списка особей) -- Аналитик
   (Провести поиск по списку особей) -- Аналитик
   (Экспортировать набор мелограмм на компьютер) -- Аналитик
}
@enduml